
package Views;

import javax.swing.JOptionPane;
import Models.Inventory;
import Models.Product;


public class LoginView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());


    public LoginView() {
        initComponents();
         setSize(930,420);
         setResizable(false); //para que no se pueda mover la pantalla
         setTitle("Ingresar al Sistema");
         setLocationRelativeTo(null);
         this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        WallPaper = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_userName = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_enter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(213, 184, 147));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WallPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo_440x420-removebg-preview.png"))); // NOI18N
        jPanel1.add(WallPaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 420));

        jPanel2.setBackground(new java.awt.Color(97, 120, 145));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(37, 52, 79));
        jLabel1.setText("INICIAR SESIÓN");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(37, 52, 79));
        jLabel2.setText("USUARIO:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(37, 52, 79));
        jLabel3.setText("CONTRASEÑA:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        txt_userName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_userName.setForeground(new java.awt.Color(37, 52, 79));
        jPanel2.add(txt_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, 35));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_password.setForeground(new java.awt.Color(37, 52, 79));
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, 35));

        btn_enter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_enter.setForeground(new java.awt.Color(37, 52, 79));
        btn_enter.setText("ACEPTAR");
        btn_enter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enterActionPerformed(evt);
            }
        });
        jPanel2.add(btn_enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 490, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enterActionPerformed
         String user = txt_userName.getText();
    String pass = String.valueOf(txt_password.getPassword());

    //  Cargar inventario solo una vez 
    if (Inventory.getProductos().isEmpty()) {
        Inventory.addProduct(new Product("Sabritas", 18.50, 50));
        Inventory.addProduct(new Product("Coca-Cola", 22.00, 40));
        Inventory.addProduct(new Product("Galletas", 15.00, 60));
        Inventory.addProduct(new Product("Pan", 12.00, 30));
        Inventory.addProduct(new Product("Leche", 28.00, 25));
    }

    //  LOGIN
    if (user.equals("admin") && pass.equals("5678")) {
        new AdminView().setVisible(true);
        this.dispose();
    } 
    else if (user.equals("cliente") && pass.equals("1234")) {
        new ClientView().setVisible(true);
        this.dispose();
    } 
    else {
        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos");
    }
    }//GEN-LAST:event_btn_enterActionPerformed

    
    public static void main(String args[]) {
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WallPaper;
    public javax.swing.JButton btn_enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField txt_password;
    public javax.swing.JTextField txt_userName;
    // End of variables declaration//GEN-END:variables
}
